In [1]:
#from usert guide to sklearn

import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([0, 0, 0, 1, 1, 1])
sss = StratifiedShuffleSplit(n_splits=5, test_size=0.5, random_state=0)
sss.get_n_splits(X, y)

5

In [2]:
print(sss)

StratifiedShuffleSplit(n_splits=5, random_state=0, test_size=0.5,
            train_size=None)


In [6]:
for train_index, test_index in sss.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print(X_train)

TRAIN: [5 2 3] TEST: [4 1 0]
[[3 4]
 [1 2]
 [3 4]]
TRAIN: [5 1 4] TEST: [0 2 3]
[[3 4]
 [3 4]
 [1 2]]
TRAIN: [5 0 2] TEST: [4 3 1]
[[3 4]
 [1 2]
 [1 2]]
TRAIN: [4 1 0] TEST: [2 3 5]
[[1 2]
 [3 4]
 [1 2]]
TRAIN: [0 5 1] TEST: [3 4 2]
[[1 2]
 [3 4]
 [3 4]]
